# HPA override — development (target Rollout, bukan Deployment)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
    type: Resource
  - resource:
      name: memory
      target:
        averageUtilization: 75
        type: Utilization
    type: Resource
  scaleTargetRef:
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: rollout
  minReplicas: 1
  maxReplicas: 3
