apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../common
- secrets.yaml
- network-policy.yaml

namespace: backend-development

namePrefix: backend-go-payment-

labels:
- pairs:
    service_group: course-project
    service_type: backend
    environment: development
    service_name: backend-go-payment
    app: backend-go-payment
  includeTemplates: true

patches:
- path: patch/rollout.yaml
- patch: |
    - op: replace
      path: /spec/selector/matchLabels/app
      value: backend-go-payment
    - op: replace
      path: /spec/template/metadata/labels/app
      value: backend-go-payment
    - op: replace
      path: /spec/template/spec/affinity/podAntiAffinity/preferredDuringSchedulingIgnoredDuringExecution/0/podAffinityTerm/labelSelector/matchLabels/app
      value: backend-go-payment
  target:
    kind: Rollout
    name: rollout
- patch: |
    - op: replace
      path: /spec/selector/app
      value: backend-go-payment
  target:
    kind: Service
- patch: |
    - op: remove
      path: /spec/strategy/canary/trafficRouting
  target:
    kind: Rollout
    name: rollout
- patch: |
    - op: remove
      path: /spec/minAvailable
  target:
    kind: PodDisruptionBudget
    name: pdb

replacements:
- source:
    kind: SecretStore
    name: vault-backend
    fieldPath: metadata.name
  targets:
  - select:
      kind: ExternalSecret
    fieldPaths:
    - spec.secretStoreRef.name
- source:
    kind: ServiceAccount
    name: backend-go
    fieldPath: metadata.name
  targets:
  - select:
      kind: SecretStore
    fieldPaths:
    - spec.provider.vault.auth.kubernetes.serviceAccountRef.name
  - select:
      kind: Rollout
    fieldPaths:
    - spec.template.spec.serviceAccountName
- source:
    kind: Service
    name: svc
    fieldPath: metadata.name
  targets:
  - select:
      kind: Rollout
    fieldPaths:
    - spec.strategy.canary.stableService
- source:
    kind: Service
    name: svc-canary
    fieldPath: metadata.name
  targets:
  - select:
      kind: Rollout
    fieldPaths:
    - spec.strategy.canary.canaryService
- source:
    kind: Rollout
    fieldPath: metadata.name
  targets:
  - select:
      kind: HorizontalPodAutoscaler
    fieldPaths:
    - spec.scaleTargetRef.name
  - select:
      kind: VerticalPodAutoscaler
    fieldPaths:
    - spec.targetRef.name
