apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: backend-development
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "backend-go-dev"
          serviceAccountRef:
            name: backend-go
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-go-secrets
  namespace: backend-development
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backend-go-payment-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_DB_URL
      remoteRef:
        key: secret/backend-go-payment/dev
        property: APP_DB_URL
    - secretKey: APP_DB_PASSWORD
      remoteRef:
        key: secret/backend-go-payment/dev
        property: APP_DB_PASSWORD
    - secretKey: APP_JWT_SECRET
      remoteRef:
        key: secret/backend-go-payment/dev
        property: APP_JWT_SECRET
    - secretKey: APP_SECRET_KEY
      remoteRef:
        key: secret/backend-go-payment/dev
        property: APP_SECRET_KEY
    - secretKey: APP_NEWRELIC_KEY
      remoteRef:
        key: secret/backend-go-payment/dev
        property: APP_NEWRELIC_KEY
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-go-pem-secrets
  namespace: backend-development
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: backend-go-payment-pem-secrets
    creationPolicy: Owner
  data:
    - secretKey: banking_private_key.pem
      remoteRef:
        key: secret/backend-go-payment/dev
        property: APP_BANKING_PRIVATE_KEY
