# ConfigMap — environment-specific configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
data:
  minAvailable: "1"
  appName: "backend-go"
  canaryService: ""
  replicas: "1"
  maxReplicas: "2"
  minReplicas: "1"
